import type { PolicyUpdate } from "@/types";

/**
 * India AI Policy Tracker — curated seed corpus.
 * Covers central legislation/guidelines, sectoral regulators, and state AI policies.
 * Dates are ISO (+05:30). Prefer official URLs; fall back to ministry hubs when PDF links rotate.
 *
 * Sources synthesised from MeitY, IndiaAI, PRS, RBI/SEBI/IRDAI/ICMR notices,
 * and public state IT/AI policy announcements (verified against secondary trackers).
 */
export const INDIA_AI_POLICIES: PolicyUpdate[] = [
  // ─── 2026 ───────────────────────────────────────────────
  {
    slug: "ifsca-cyber-ai-mii-guidelines-2026",
    title: "IFSCA cybersecurity guidelines for MIIs (AI risk, 6-hour reporting)",
    jurisdiction: "central",
    jurisdictionLabel: "IFSCA · GIFT City",
    agency: "IFSCA",
    sector: "BFSI / Markets",
    instrument: "guidelines",
    status: "in-force",
    publishedAt: "2026-04-20T10:00:00+05:30",
    summary:
      "Cybersecurity and cyber-resilience guidelines for market infrastructure institutions in GIFT City covering AI-related cyber risk, six-hour incident reporting, and post-quantum readiness expectations.",
    sourceUrl: "https://ifsca.gov.in/",
    tags: ["ifsca", "gift-city", "cyber", "incident-reporting"],
  },
  {
    slug: "it-rules-2026-deepfake-sgi-in-force",
    title: "IT Rules 2026 Amendment on deepfakes / SGI comes into force",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Platforms / Intermediaries",
    instrument: "rules",
    status: "in-force",
    publishedAt: "2026-02-20T00:00:00+05:30",
    summary:
      "Amended IT Rules on synthetically generated information (SGI) / deepfakes take effect — including accelerated takedown timelines and AI-generated content labelling duties for covered intermediaries.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["it-rules", "deepfake", "labelling", "takedown"],
  },
  {
    slug: "india-ai-impact-summit-2026",
    title: "India AI Impact Summit 2026 (Bharat Mandapam)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY / IndiaAI",
    agency: "MeitY",
    sector: "Cross-sector",
    instrument: "mission",
    status: "announced",
    publishedAt: "2026-02-16T10:00:00+05:30",
    summary:
      "New Delhi hosted the India AI Impact Summit 2026, with multilateral declarations and domestic signalling on safe, trusted AI aligned to the IndiaAI Mission pillars.",
    sourceUrl: "https://indiaai.gov.in/",
    tags: ["summit", "indiaai", "diplomacy"],
  },
  {
    slug: "it-rules-2026-amendment-notified",
    title: "IT Rules 2026 Amendment notified (3-hour takedown, AI labelling)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Platforms / Intermediaries",
    instrument: "rules",
    status: "in-force",
    publishedAt: "2026-02-10T10:00:00+05:30",
    summary:
      "Notification of IT Rules amendments targeting synthetically generated / deepfake content — notable for short takedown clocks and mandatory labelling of AI-generated media for significant social media intermediaries.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["it-rules", "deepfake", "labelling"],
  },
  {
    slug: "maharashtra-ai-policy-2026",
    title: "Maharashtra AI Policy 2026 approved",
    jurisdiction: "state",
    jurisdictionLabel: "Maharashtra",
    agency: "Government of Maharashtra",
    sector: "Cross-sector",
    instrument: "mission",
    status: "in-force",
    publishedAt: "2026-01-15T10:00:00+05:30",
    summary:
      "Cabinet-approved state AI policy targeting ~₹10,000 Cr investment and ~1.5 lakh jobs by 2031 — Maharashtra AI Mission, six CoEs (health, agri, education, urban, Marathi, finance), AI innovation cities, and mandatory annual AI readiness audits for covered entities.",
    sourceUrl: "https://www.maharashtra.gov.in/",
    tags: ["state-policy", "maharashtra", "skilling", "coe"],
  },

  // ─── 2025 ───────────────────────────────────────────────
  {
    slug: "it-rules-sgi-amendment-nov-2025",
    title: "IT Rules amendment on Synthetically Generated Information notified",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Platforms / Intermediaries",
    instrument: "rules",
    status: "in-force",
    publishedAt: "2025-11-15T10:00:00+05:30",
    summary:
      "MeitY notifies amendments addressing synthetically generated information — the legislative backbone for later deepfake labelling and takedown timelines.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["it-rules", "sgi", "deepfake"],
  },
  {
    slug: "dpdp-rules-2025-notified",
    title: "DPDP Rules 2025 notified (phased compliance window)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY / Data Protection Board",
    agency: "MeitY",
    sector: "Privacy / Data",
    instrument: "rules",
    status: "in-force",
    publishedAt: "2025-11-13T10:00:00+05:30",
    summary:
      "Implementing rules under the Digital Personal Data Protection Act, 2023 — consent, purpose limitation, security, and breach duties with a phased compliance runway. Directly shapes lawful AI training and inference on personal data.",
    sourceUrl: "https://www.meity.gov.in/data-protection-framework",
    tags: ["dpdp", "privacy", "rules", "training-data"],
  },
  {
    slug: "meity-india-ai-governance-guidelines-2025",
    title: "MeitY India AI Governance Guidelines (7 Sutras)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY / IndiaAI",
    agency: "MeitY",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "in-force",
    publishedAt: "2025-11-05T10:00:00+05:30",
    summary:
      "Principle-based India AI Governance Guidelines — seven sutras (trust, people-first, innovation over restraint, fairness, accountability, understandability, safety). Proposes AIGG, TPEC, and AI Safety Institute architecture with graded, voluntary-first compliance.",
    sourceUrl: "https://indiaai.gov.in/",
    tags: ["governance", "guidelines", "aisi", "aigg"],
  },
  {
    slug: "draft-it-rules-deepfake-oct-2025",
    title: "Draft IT Rules amendment on deepfakes / SGI (consultation)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Platforms / Intermediaries",
    instrument: "rules",
    status: "consultation",
    publishedAt: "2025-10-22T10:00:00+05:30",
    summary:
      "Draft amendments published for consultation on deepfake and synthetically generated information obligations for intermediaries — precursor to the 2026 notifications.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["it-rules", "draft", "deepfake"],
  },
  {
    slug: "cdsco-samd-ai-ml-draft-2025",
    title: "CDSCO draft guidance on medical device software (SaMD/SiMD, AI/ML)",
    jurisdiction: "central",
    jurisdictionLabel: "CDSCO / MoHFW",
    agency: "CDSCO",
    sector: "Healthcare",
    instrument: "sectoral",
    status: "draft",
    publishedAt: "2025-10-21T10:00:00+05:30",
    summary:
      "Draft guidance for software as/in a medical device covering AI/ML lifecycle expectations for clinical software marketed in India.",
    sourceUrl: "https://cdsco.gov.in/",
    tags: ["cdsco", "samd", "health-ai", "draft"],
  },
  {
    slug: "rbi-free-ai-framework-2025",
    title: "RBI FREE-AI Framework (7 sutras, 26 recommendations)",
    jurisdiction: "central",
    jurisdictionLabel: "RBI",
    agency: "RBI",
    sector: "BFSI",
    instrument: "sectoral",
    status: "in-force",
    publishedAt: "2025-08-13T10:00:00+05:30",
    summary:
      "Framework for Responsible and Ethical Enablement of AI in the financial sector — seven sutras and 26 recommendations spanning model risk, consumer protection, governance, and operational resilience for banks and NBFCs.",
    sourceUrl: "https://www.rbi.org.in/",
    tags: ["rbi", "free-ai", "bfsi", "model-risk"],
  },
  {
    slug: "telangana-tgdex-2025",
    title: "Telangana TGDeX AI-ready data exchange launched",
    jurisdiction: "state",
    jurisdictionLabel: "Telangana",
    agency: "Government of Telangana",
    sector: "Public services",
    instrument: "mission",
    status: "in-force",
    publishedAt: "2025-07-01T10:00:00+05:30",
    summary:
      "State AI-ready data exchange (TGDeX) to unlock non-personal / governed datasets for public-service AI and startup innovation under the Telangana AI roadmap.",
    sourceUrl: "https://it.telangana.gov.in/",
    tags: ["telangana", "datasets", "public-sector"],
  },
  {
    slug: "sebi-ai-ml-securities-consultation-2025",
    title: "SEBI consultation paper on AI/ML in securities markets",
    jurisdiction: "central",
    jurisdictionLabel: "SEBI",
    agency: "SEBI",
    sector: "BFSI / Markets",
    instrument: "sectoral",
    status: "consultation",
    publishedAt: "2025-06-20T10:00:00+05:30",
    summary:
      "Consultation on use of AI/ML by market participants and intermediaries — disclosure, governance, and investor-protection questions for securities markets.",
    sourceUrl: "https://www.sebi.gov.in/",
    tags: ["sebi", "securities", "consultation"],
  },
  {
    slug: "odisha-ai-policy-2025",
    title: "Odisha AI Policy 2025 approved",
    jurisdiction: "state",
    jurisdictionLabel: "Odisha",
    agency: "Government of Odisha",
    sector: "Cross-sector",
    instrument: "mission",
    status: "in-force",
    publishedAt: "2025-05-01T10:00:00+05:30",
    summary:
      "State AI policy focused on talent development, public-service AI adoption, and building capacity to create and operate AI systems in Odisha.",
    sourceUrl: "https://odisha.gov.in/",
    tags: ["odisha", "state-policy", "skilling"],
  },
  {
    slug: "sebi-algo-trading-retail-2025",
    title: "SEBI: safer retail participation in algorithmic trading (w.e.f. Apr 2026)",
    jurisdiction: "central",
    jurisdictionLabel: "SEBI",
    agency: "SEBI",
    sector: "BFSI / Markets",
    instrument: "sectoral",
    status: "in-force",
    publishedAt: "2025-02-04T10:00:00+05:30",
    summary:
      "Measures for safer retail participation in algo trading — relevant where brokers and fintechs use AI/ML-driven execution and recommendation stacks.",
    sourceUrl: "https://www.sebi.gov.in/",
    tags: ["sebi", "algo-trading", "retail"],
  },
  {
    slug: "indiaai-governance-guidelines-report-jan-2025",
    title: "IndiaAI report on AI governance guidelines development",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY / IndiaAI",
    agency: "MeitY",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "announced",
    publishedAt: "2025-01-06T10:00:00+05:30",
    summary:
      "IndiaAI publishes developmental report feeding into the later India AI Governance Guidelines — maps institutional options and risk framing for India.",
    sourceUrl: "https://indiaai.gov.in/",
    tags: ["indiaai", "governance", "report"],
  },
  {
    slug: "meity-draft-ai-governance-guidelines-jan-2025",
    title: "MeitY draft AI Governance Guidelines (public consultation)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "consultation",
    publishedAt: "2025-01-06T09:00:00+05:30",
    summary:
      "Draft AI governance guidelines opened for consultation — precursor to the November 2025 sutra-based India AI Governance Guidelines.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["meity", "draft", "governance"],
  },
  {
    slug: "draft-dpdp-rules-2025",
    title: "Draft DPDP Rules 2025 published",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Privacy / Data",
    instrument: "rules",
    status: "consultation",
    publishedAt: "2025-01-03T10:00:00+05:30",
    summary:
      "Draft rules under DPDP Act published for consultation — consent managers, reasonable security, and processing conditions that AI product teams must design for.",
    sourceUrl: "https://www.meity.gov.in/data-protection-framework",
    tags: ["dpdp", "draft-rules", "privacy"],
  },

  // ─── 2024 ───────────────────────────────────────────────
  {
    slug: "telangana-ai-roadmap-2024",
    title: "Telangana AI-Powered Strategy Roadmap",
    jurisdiction: "state",
    jurisdictionLabel: "Telangana",
    agency: "Government of Telangana",
    sector: "Public services",
    instrument: "mission",
    status: "in-force",
    publishedAt: "2024-09-01T10:00:00+05:30",
    summary:
      "State roadmap aiming AI-driven services for 1+ crore citizens by 2027 across agri, health, education, and mobility — local datasets, AI City near Hyderabad, and large-scale skilling targets.",
    sourceUrl: "https://it.telangana.gov.in/",
    tags: ["telangana", "roadmap", "citizen-services"],
  },
  {
    slug: "telangana-ai-advisory-council-2024",
    title: "Telangana AI Roadmap & Advisory Council announced",
    jurisdiction: "state",
    jurisdictionLabel: "Telangana",
    agency: "Government of Telangana",
    sector: "Cross-sector",
    instrument: "mission",
    status: "announced",
    publishedAt: "2024-09-01T09:00:00+05:30",
    summary:
      "Advisory council and institutional setup accompanying Telangana’s AI roadmap — governance overlay for state AI programmes.",
    sourceUrl: "https://it.telangana.gov.in/",
    tags: ["telangana", "advisory-council"],
  },
  {
    slug: "tamil-nadu-tnaim-go-25-2024",
    title: "Tamil Nadu AI Mission (TNAIM) — G.O. Ms. No. 25, 2024",
    jurisdiction: "state",
    jurisdictionLabel: "Tamil Nadu",
    agency: "Government of Tamil Nadu",
    sector: "Public services",
    instrument: "mission",
    status: "in-force",
    publishedAt: "2024-10-09T10:00:00+05:30",
    summary:
      "G.O. establishing Tamil Nadu Artificial Intelligence Mission (TNAIM) with budgeted implementation via TNeGA — safe & ethical AI for governance, building on the state’s TAM-DEF / DEEP-MAX frameworks.",
    sourceUrl: "https://www.tn.gov.in/",
    tags: ["tamil-nadu", "tnaim", "ethical-ai"],
  },
  {
    slug: "tamil-nadu-safe-ethical-ai-policy-refresh-2024",
    title: "Tamil Nadu Safe & Ethical AI Policy (2024 refresh)",
    jurisdiction: "state",
    jurisdictionLabel: "Tamil Nadu",
    agency: "Government of Tamil Nadu",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "in-force",
    publishedAt: "2024-08-01T10:00:00+05:30",
    summary:
      "State policy for safe and ethical AI — TAM-DEF evaluation dimensions and DEEP-MAX scorecard for public-sector AI procurement and deployment.",
    sourceUrl: "https://tnreginet.gov.in/portal/document/TN_Policy_for_Safe_and_Ethical_AI.PDF",
    tags: ["tamil-nadu", "ethical-ai", "procurement"],
  },
  {
    slug: "eci-ai-deepfake-advisory-2024",
    title: "Election Commission advisory on AI / deepfakes in elections",
    jurisdiction: "central",
    jurisdictionLabel: "Election Commission of India",
    agency: "ECI",
    sector: "Elections",
    instrument: "advisory",
    status: "in-force",
    publishedAt: "2024-06-01T10:00:00+05:30",
    summary:
      "ECI guidance on AI-generated / deepfake content in the electoral context — labelling, takedown coordination, and platform responsibilities during election periods.",
    sourceUrl: "https://www.eci.gov.in/",
    tags: ["elections", "deepfake", "eci"],
  },
  {
    slug: "meity-untested-ai-clarification-2024",
    title: "MeitY clarification on “untested AI” advisory",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Platforms / Intermediaries",
    instrument: "advisory",
    status: "in-force",
    publishedAt: "2024-03-15T10:00:00+05:30",
    summary:
      "Clarification walking back / narrowing the March 2024 advisory language on “untested AI” — important compliance history for platforms and AI startups.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["meity", "advisory", "clarification"],
  },
  {
    slug: "indiaai-mission-cabinet-2024",
    title: "IndiaAI Mission approved (₹10,371.92 crore)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY / Cabinet",
    agency: "MeitY",
    sector: "Infrastructure",
    instrument: "mission",
    status: "in-force",
    publishedAt: "2024-03-01T10:00:00+05:30",
    summary:
      "Cabinet approval of IndiaAI Mission — seven pillars including compute (≥10k GPUs ambition), innovation centre for foundation models, datasets platform, applications, future skills, startup financing, and safe & trusted AI.",
    sourceUrl: "https://indiaai.gov.in/",
    tags: ["indiaai", "mission", "compute", "cabinet"],
  },
  {
    slug: "meity-ai-advisory-march-2024",
    title: "MeitY advisory on AI / deepfakes (March 2024)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Platforms / Intermediaries",
    instrument: "advisory",
    status: "superseded",
    publishedAt: "2024-03-01T09:00:00+05:30",
    summary:
      "Controversial intermediary advisory on AI-generated content and “untested” models — later clarified; still a milestone in India’s soft-law approach to generative AI harms.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["meity", "advisory", "deepfake"],
  },
  {
    slug: "karnataka-ai-ml-admin-unit-2024",
    title: "Karnataka AI/ML administration unit announced",
    jurisdiction: "state",
    jurisdictionLabel: "Karnataka",
    agency: "Government of Karnataka",
    sector: "Public services",
    instrument: "mission",
    status: "announced",
    publishedAt: "2024-01-15T10:00:00+05:30",
    summary:
      "State move to institutionalise AI/ML capacity inside administration — part of Karnataka’s push to brand as an AI-native destination alongside later IT Policy 2025–30 incentives.",
    sourceUrl: "https://itbt.karnataka.gov.in/",
    tags: ["karnataka", "public-sector", "capacity"],
  },
  {
    slug: "maharashtra-google-ai-mou-2024",
    title: "Maharashtra MoU with Google on AI",
    jurisdiction: "state",
    jurisdictionLabel: "Maharashtra",
    agency: "Government of Maharashtra",
    sector: "Cross-sector",
    instrument: "mission",
    status: "announced",
    publishedAt: "2024-01-10T10:00:00+05:30",
    summary:
      "State–industry MoU with Google on AI capacity, skilling, and public digital programmes — precursor energy to Maharashtra’s fuller AI Policy 2026.",
    sourceUrl: "https://www.maharashtra.gov.in/",
    tags: ["maharashtra", "mou", "skilling"],
  },
  {
    slug: "andhra-pradesh-ai-for-ap-2024",
    title: "Andhra Pradesh “AI for AP” initiative",
    jurisdiction: "state",
    jurisdictionLabel: "Andhra Pradesh",
    agency: "Government of Andhra Pradesh",
    sector: "Public services",
    instrument: "mission",
    status: "announced",
    publishedAt: "2024-01-08T10:00:00+05:30",
    summary:
      "State AI programme with industry partners aimed at citizen services and skilling under the “AI for AP” banner.",
    sourceUrl: "https://www.ap.gov.in/",
    tags: ["andhra-pradesh", "citizen-services"],
  },
  {
    slug: "gujarat-ai-taskforce-gift-2024",
    title: "Gujarat AI taskforce with Microsoft at GIFT City",
    jurisdiction: "state",
    jurisdictionLabel: "Gujarat",
    agency: "Government of Gujarat",
    sector: "BFSI / Markets",
    instrument: "mission",
    status: "announced",
    publishedAt: "2024-01-05T10:00:00+05:30",
    summary:
      "Gujarat–Microsoft AI collaboration centred on GIFT City — fintech, IFSC adjacency, and state AI capacity building.",
    sourceUrl: "https://gujaratindia.gov.in/",
    tags: ["gujarat", "gift-city", "fintech"],
  },
  {
    slug: "karnataka-it-policy-2025-30-ai",
    title: "Karnataka IT Policy 2025–30 (AI-native incentives)",
    jurisdiction: "state",
    jurisdictionLabel: "Karnataka",
    agency: "Government of Karnataka",
    sector: "Infrastructure",
    instrument: "mission",
    status: "in-force",
    publishedAt: "2025-11-20T10:00:00+05:30",
    summary:
      "IT Policy 2025–30 with ~₹967 Cr incentives — explicit AI/deep-tech focus, expansion beyond Bengaluru (Mysuru, Mangaluru, Hubballi, etc.), and “AI-native destination” branding.",
    sourceUrl: "https://itbt.karnataka.gov.in/",
    tags: ["karnataka", "it-policy", "incentives", "tier-2"],
  },
  {
    slug: "maharashtra-mahaagri-ai-policy-2025",
    title: "Maharashtra MahaAgri-AI Policy 2025–29",
    jurisdiction: "state",
    jurisdictionLabel: "Maharashtra",
    agency: "Government of Maharashtra",
    sector: "Agriculture",
    instrument: "mission",
    status: "in-force",
    publishedAt: "2025-06-01T10:00:00+05:30",
    summary:
      "Sectoral state policy for AI in agriculture — advisory, crop, and agri-stack use cases with dedicated outlay signalling.",
    sourceUrl: "https://www.maharashtra.gov.in/",
    tags: ["maharashtra", "agriculture", "agri-ai"],
  },

  // ─── 2023 and earlier foundational ─────────────────────
  {
    slug: "dpdp-act-2023",
    title: "Digital Personal Data Protection Act, 2023 enacted",
    jurisdiction: "central",
    jurisdictionLabel: "Parliament / MeitY",
    agency: "MeitY",
    sector: "Privacy / Data",
    instrument: "legislation",
    status: "in-force",
    publishedAt: "2023-08-11T10:00:00+05:30",
    summary:
      "India’s primary personal-data statute — consent, purpose limitation, fiduciary duties, and penalties (up to ₹250 Cr) that govern personal data used to train or operate AI systems.",
    sourceUrl: "https://www.meity.gov.in/data-protection-framework",
    tags: ["dpdp", "legislation", "privacy"],
  },
  {
    slug: "telecommunications-act-2023",
    title: "Telecommunications Act, 2023",
    jurisdiction: "central",
    jurisdictionLabel: "DoT / Parliament",
    agency: "DoT",
    sector: "Telecom",
    instrument: "legislation",
    status: "in-force",
    publishedAt: "2023-12-24T10:00:00+05:30",
    summary:
      "Modern telecom statute replacing colonial-era telegraph law — relevant to AI voice bots, interception rules, and telecom-adjacent AI services.",
    sourceUrl: "https://dot.gov.in/",
    tags: ["telecom", "legislation"],
  },
  {
    slug: "icmr-ai-biomedical-ethics-2023",
    title: "ICMR ethical guidelines for AI in biomedical research & healthcare",
    jurisdiction: "central",
    jurisdictionLabel: "ICMR",
    agency: "ICMR",
    sector: "Healthcare",
    instrument: "sectoral",
    status: "in-force",
    publishedAt: "2023-03-01T10:00:00+05:30",
    summary:
      "Ethics framework for AI in biomedical research and healthcare — consent, bias, clinical validation, and accountability expectations for Indian health-AI builders.",
    sourceUrl: "https://www.icmr.gov.in/",
    tags: ["icmr", "health-ai", "ethics"],
  },
  {
    slug: "nasscom-genai-guidelines-2023",
    title: "NASSCOM GenAI guidelines",
    jurisdiction: "central",
    jurisdictionLabel: "Industry (NASSCOM)",
    agency: "NASSCOM",
    sector: "Cross-sector",
    instrument: "industry",
    status: "in-force",
    publishedAt: "2023-06-01T10:00:00+05:30",
    summary:
      "Industry self-regulatory guidance for generative AI deployment by Indian IT/BPM and product companies.",
    sourceUrl: "https://nasscom.in/",
    tags: ["nasscom", "genai", "industry"],
  },
  {
    slug: "it-rules-2021",
    title: "IT (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Platforms / Intermediaries",
    instrument: "rules",
    status: "in-force",
    publishedAt: "2021-02-25T10:00:00+05:30",
    summary:
      "Core intermediary due-diligence rules — later amended for deepfakes/SGI. Still the primary soft-law spine for platform AI content liability in India.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["it-rules", "intermediaries"],
  },
  {
    slug: "niti-responsible-ai-part2-2021",
    title: "NITI Aayog — Operationalising Responsible AI (Part 2)",
    jurisdiction: "central",
    jurisdictionLabel: "NITI Aayog",
    agency: "NITI Aayog",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "in-force",
    publishedAt: "2021-08-01T10:00:00+05:30",
    summary:
      "Follow-on to Responsible AI Part 1 — operational principles for public and private AI adoption in India.",
    sourceUrl: "https://www.niti.gov.in/",
    tags: ["niti", "responsible-ai"],
  },
  {
    slug: "niti-responsible-ai-part1-2020",
    title: "NITI Aayog — Responsible AI for All (Part 1)",
    jurisdiction: "central",
    jurisdictionLabel: "NITI Aayog",
    agency: "NITI Aayog",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "in-force",
    publishedAt: "2020-02-01T10:00:00+05:30",
    summary:
      "Foundational voluntary Responsible AI principles for India — fairness, transparency, accountability themes that later MeitY guidelines still echo.",
    sourceUrl: "https://www.niti.gov.in/",
    tags: ["niti", "responsible-ai"],
  },
  {
    slug: "tamil-nadu-safe-ethical-ai-2020",
    title: "Tamil Nadu Safe & Ethical AI Policy 2020 (first version)",
    jurisdiction: "state",
    jurisdictionLabel: "Tamil Nadu",
    agency: "Government of Tamil Nadu",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "superseded",
    publishedAt: "2020-01-15T10:00:00+05:30",
    summary:
      "India’s early state-level safe & ethical AI policy — introduced TAM-DEF and DEEP-MAX concepts later refreshed in 2024.",
    sourceUrl: "https://tnreginet.gov.in/portal/document/TN_Policy_for_Safe_and_Ethical_AI.PDF",
    tags: ["tamil-nadu", "ethical-ai", "first-mover"],
  },
  {
    slug: "niti-national-strategy-ai-2018",
    title: "NITI Aayog National Strategy for Artificial Intelligence (#AIForAll)",
    jurisdiction: "central",
    jurisdictionLabel: "NITI Aayog",
    agency: "NITI Aayog",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "in-force",
    publishedAt: "2018-06-01T10:00:00+05:30",
    summary:
      "India’s flagship national AI strategy discussion paper — healthcare, agriculture, education, smart cities, and smart mobility as priority sectors under #AIForAll.",
    sourceUrl: "https://www.niti.gov.in/",
    tags: ["niti", "national-strategy", "aiforall"],
  },
  {
    slug: "sebi-ai-ml-mutual-funds-2019",
    title: "SEBI reporting requirements for AI/ML in mutual funds (2019)",
    jurisdiction: "central",
    jurisdictionLabel: "SEBI",
    agency: "SEBI",
    sector: "BFSI / Markets",
    instrument: "sectoral",
    status: "in-force",
    publishedAt: "2019-05-09T10:00:00+05:30",
    summary:
      "Early SEBI circular requiring reporting of AI/ML applications used by mutual funds — among India’s first sectoral AI disclosure rules.",
    sourceUrl: "https://www.sebi.gov.in/",
    tags: ["sebi", "mutual-funds", "disclosure"],
  },
  {
    slug: "sebi-ai-ml-mii-2019",
    title: "SEBI reporting for AI/ML at market infrastructure institutions (2019)",
    jurisdiction: "central",
    jurisdictionLabel: "SEBI",
    agency: "SEBI",
    sector: "BFSI / Markets",
    instrument: "sectoral",
    status: "in-force",
    publishedAt: "2019-01-31T10:00:00+05:30",
    summary:
      "Reporting framework for AI/ML systems offered/used by MIIs — exchanges, depositories, clearing corporations.",
    sourceUrl: "https://www.sebi.gov.in/",
    tags: ["sebi", "mii", "disclosure"],
  },
  {
    slug: "irdai-emerging-tech-insurance-2020",
    title: "IRDAI emerging technologies in insurance — adoption strategies",
    jurisdiction: "central",
    jurisdictionLabel: "IRDAI",
    agency: "IRDAI",
    sector: "BFSI / Insurance",
    instrument: "sectoral",
    status: "in-force",
    publishedAt: "2020-12-09T10:00:00+05:30",
    summary:
      "IRDAI guidance on emerging tech (including AI) adoption strategies for insurers and ecosystem stakeholders.",
    sourceUrl: "https://www.irdai.gov.in/",
    tags: ["irdai", "insurance", "emerging-tech"],
  },
  {
    slug: "rbi-digital-lending-directions-2022",
    title: "RBI Master Directions on Digital Lending (2022)",
    jurisdiction: "central",
    jurisdictionLabel: "RBI",
    agency: "RBI",
    sector: "BFSI",
    instrument: "sectoral",
    status: "in-force",
    publishedAt: "2022-09-02T10:00:00+05:30",
    summary:
      "Digital lending directions with data, consent, and LSPs — foundational for AI-driven credit underwriting and collections stacks in India.",
    sourceUrl: "https://www.rbi.org.in/",
    tags: ["rbi", "digital-lending", "fintech"],
  },
  {
    slug: "national-data-governance-framework-draft-2022",
    title: "Draft National Data Governance Framework Policy",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Privacy / Data",
    instrument: "guidelines",
    status: "draft",
    publishedAt: "2022-05-01T10:00:00+05:30",
    summary:
      "Draft framework for non-personal data / government data sharing — important backdrop for IndiaAI datasets pillar and public-sector AI.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["data-governance", "draft", "datasets"],
  },
  {
    slug: "puttaswamy-privacy-2017",
    title: "Puttaswamy judgment — privacy as a fundamental right",
    jurisdiction: "central",
    jurisdictionLabel: "Supreme Court of India",
    agency: "Supreme Court",
    sector: "Privacy / Data",
    instrument: "court",
    status: "in-force",
    publishedAt: "2017-08-24T10:00:00+05:30",
    summary:
      "Constitutional foundation for India’s privacy regime — underpins DPDP and any AI system processing personal data of individuals in India.",
    sourceUrl: "https://main.sci.gov.in/",
    tags: ["supreme-court", "privacy", "constitutional"],
  },
  {
    slug: "it-act-2000",
    title: "Information Technology Act, 2000 (as amended)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY / Parliament",
    agency: "MeitY",
    sector: "Platforms / Intermediaries",
    instrument: "legislation",
    status: "in-force",
    publishedAt: "2000-10-17T10:00:00+05:30",
    summary:
      "India’s primary cyber statute — intermediary safe harbour, cyber offences, and the parent authority for IT Rules that now reach deepfakes and AI-generated content. Digital India Act proposed as eventual replacement (not yet enacted).",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["it-act", "legislation", "intermediaries"],
  },
  {
    slug: "meity-ai-governance-framework-2026-ops",
    title: "MeitY AI governance operational expectations (2026 desk note)",
    jurisdiction: "central",
    jurisdictionLabel: "MeitY (Central)",
    agency: "MeitY",
    sector: "Cross-sector",
    instrument: "guidelines",
    status: "announced",
    publishedAt: "2026-07-22T09:00:00+05:30",
    summary:
      "Post-guidelines operational push: purpose documentation, logging, and human oversight expectations for high-impact AI deployers — tracked for founders alongside the formal India AI Governance Guidelines.",
    sourceUrl: "https://www.meity.gov.in/",
    tags: ["governance", "compliance", "high-risk"],
  },
  {
    slug: "delhi-madras-hc-deepfake-personality-2026",
    title: "Delhi & Madras HC deepfake / personality-rights rulings (wave)",
    jurisdiction: "central",
    jurisdictionLabel: "High Courts",
    agency: "Judiciary",
    sector: "Platforms / Intermediaries",
    instrument: "court",
    status: "in-force",
    publishedAt: "2026-06-01T10:00:00+05:30",
    summary:
      "High Court orders and injunctions on deepfakes and personality rights — de facto product requirements for generative media startups ahead of fuller statutory labelling rules.",
    sourceUrl: "https://indiaaibrief.com/news/delhi-madras-high-court-deepfake-rulings",
    tags: ["court", "deepfake", "personality-rights"],
  },
];

export function uniquePolicySectors(
  updates: PolicyUpdate[] = INDIA_AI_POLICIES,
): string[] {
  return Array.from(new Set(updates.map((u) => u.sector))).sort();
}

export function uniquePolicyAgencies(
  updates: PolicyUpdate[] = INDIA_AI_POLICIES,
): string[] {
  return Array.from(
    new Set(updates.map((u) => u.agency ?? u.jurisdictionLabel)),
  ).sort();
}

export function uniquePolicyInstruments(
  updates: PolicyUpdate[] = INDIA_AI_POLICIES,
): string[] {
  return Array.from(
    new Set(updates.map((u) => u.instrument).filter(Boolean) as string[]),
  ).sort();
}

export function policyCoverageStats(updates: PolicyUpdate[] = INDIA_AI_POLICIES) {
  const central = updates.filter((u) => u.jurisdiction === "central").length;
  const state = updates.filter((u) => u.jurisdiction === "state").length;
  const states = new Set(
    updates.filter((u) => u.jurisdiction === "state").map((u) => u.jurisdictionLabel),
  ).size;
  return {
    total: updates.length,
    central,
    state,
    statesCovered: states,
    sectors: uniquePolicySectors(updates).length,
  };
}
