/** Client-safe highlight terms (mirrors classify keyword lists). */
export function getIndiaHighlightTerms(): string[] {
  return [
    "india",
    "indian",
    "bharat",
    "meity",
    "niti aayog",
    "dpiit",
    "digital india",
    "indiaai",
    "bhashini",
    "bangalore",
    "bengaluru",
    "mumbai",
    "delhi",
    "hyderabad",
    "chennai",
    "pune",
    "kolkata",
    "gurgaon",
    "gurugram",
    "noida",
    "tcs",
    "infosys",
    "wipro",
    "hcl",
    "reliance",
    "tata",
    "ola",
    "sarvam",
    "krutrim",
    "corover",
    "ai4bharat",
    "rbi",
    "sebi",
    "trai",
    "cci",
    "dpdp",
    "crore",
    "lakh",
    "₹",
    "inr",
    "hindi",
    "tamil",
    "telugu",
    "bengali",
    "marathi",
    "kannada",
  ];
}
